# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Termalin.Termalin
PackageVersion: 0.1.45
InstallerLocale: en-US
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
AppsAndFeaturesEntries:
- DisplayName: Termalin
  Publisher: Termalin
  ProductCode: '{B7A5D1E8-4C1F-4A57-9A2E-7D30F1B6C9D4}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://termal.in/download/Termalin-Setup-0.1.45.exe
  InstallerSha256: 7B4734584DD1F673CAFEA77E009B5A6E3C63DAD49272F3B64EA16E73EF9F0E7F
ManifestType: installer
ManifestVersion: 1.12.0
